// Local browser recordings. Uses the isolated QA server and public test account.
import {chromium} from 'playwright';
import {account} from '../../server/test/helpers';
import {writeFileSync,mkdirSync} from 'node:fs';
const root='output/sprout-family-film';
mkdirSync(`${root}/capture`,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const manifest:any={};
async function record(name:string,path:string,duration:number,setup:Function,action:Function){
 const context=await browser.newContext({viewport:{width:1600,height:720},recordVideo:{dir:`${root}/capture`,size:{width:1600,height:720}}});
 const started=Date.now();const page=await context.newPage();
 await page.exposeFunction('__qaWallet',async({method,params}:any)=>{if(method==='eth_accounts'||method==='eth_requestAccounts')return[account.address];if(method==='eth_chainId')return'0x1237';if(method==='personal_sign')return account.signMessage({message:Buffer.from(params[0].slice(2),'hex').toString('utf8')});if(method==='wallet_switchEthereumChain'||method==='wallet_addEthereumChain')return null;throw new Error(method);});
 await page.addInitScript(()=>{(window as any).ethereum={request:(a:any)=>(window as any).__qaWallet(a),on:()=>{},removeListener:()=>{}};});
 await page.goto(`http://127.0.0.1:5197${path}`);await page.waitForLoadState('networkidle');
 await setup(page);await page.waitForTimeout(500);
 // Visible cursor reflects actual automated browser interaction.
 await page.evaluate(()=>{const el=document.createElement('div');el.id='film-cursor';el.style.cssText='position:fixed;width:22px;height:28px;top:600px;left:1300px;z-index:9999;pointer-events:none;filter:drop-shadow(0 2px 2px #0003);transition:left .22s ease,top .22s ease';el.innerHTML='<svg viewBox="0 0 24 30"><path d="M2 2L21 18L13 19L9 28Z" fill="#283022" stroke="white" stroke-width="2"/></svg>';document.body.append(el);});
 const start=(Date.now()-started)/1000;const captureStart=Date.now();
 await action(page);
 await page.waitForTimeout(Math.max(0,duration*1000-(Date.now()-captureStart)));
 const video=page.video();await context.close();manifest[name]={path:await video!.path(),start,duration};console.log(`${name} recorded`);
}
async function click(p:any,locator:any){const b=await locator.boundingBox();if(b)await p.evaluate(({x,y}:any)=>{const c=document.getElementById('film-cursor')!;c.style.left=`${x}px`;c.style.top=`${y}px`;},{x:b.x+b.width/2,y:b.y+b.height/2});await p.waitForTimeout(250);await locator.click();}
const connect=async(p:any)=>{await p.getByRole('button',{name:'Connect wallet',exact:true}).first().click();await p.getByRole('button',{name:/Lock/}).waitFor();await p.waitForLoadState('networkidle');};
await record('assets','/asset-passports',6,async p=>{await p.evaluate(()=>scrollTo(0,160));},async p=>{await p.waitForTimeout(750);const search=p.getByLabel('Search assets');await click(p,search);await search.pressSequentially('NVIDIA',{delay:100});await p.waitForTimeout(400);await click(p,p.getByRole('button',{name:'NV NVDA NVIDIA'}));await p.waitForTimeout(1200);await search.fill('');});
await record('records','/tax-garden',8,async p=>{await connect(p);await p.getByRole('button',{name:'Review ETH record',exact:true}).click();await p.getByRole('dialog').getByLabel('Cost basis').fill('');await p.getByRole('dialog').getByRole('button',{name:'Save record'}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await p.evaluate(()=>scrollTo(0,170));},async p=>{await p.waitForTimeout(900);await click(p,p.getByRole('button',{name:'Review ETH record',exact:true}).first());const d=p.getByRole('dialog');await p.waitForTimeout(650);await click(p,d.getByLabel('Cost basis'));await d.getByLabel('Cost basis').fill('');await d.getByLabel('Cost basis').pressSequentially('40.00',{delay:190});await p.waitForTimeout(800);await click(p,d.getByRole('button',{name:'Save record'}));await d.waitFor({state:'hidden'});});
await record('planner','/family-investing',10,async p=>{await connect(p);const del=p.getByRole('button',{name:'Delete saved plan',exact:true});if(await del.count()){await del.click();await p.getByRole('button',{name:'Confirm delete saved plan'}).click();await p.getByLabel('Give your goal a name').waitFor();}await p.evaluate(()=>scrollTo(0,300));},async p=>{await p.waitForTimeout(500);await click(p,p.getByRole('button',{name:'A first apartment',exact:true}));await p.getByLabel('Target amount',{exact:false}).fill('25000');await p.getByLabel('Time to grow').selectOption('18');await p.waitForTimeout(700);await click(p,p.getByRole('button',{name:'Choose ownership',exact:true}));await p.getByLabel('Your US state',{exact:true}).selectOption('NY');await p.waitForTimeout(500);await click(p,p.getByRole('radio',{name:'Custodial account',exact:false}));await p.waitForTimeout(650);await click(p,p.getByRole('button',{name:'Review your plan',exact:true}));await p.getByRole('checkbox').check();await p.waitForTimeout(900);await click(p,p.getByRole('button',{name:'Save my family plan',exact:true}));await p.getByRole('status').filter({hasText:'Your family plan is saved'}).waitFor();await p.evaluate(()=>scrollTo({top:320,behavior:'smooth'}));});
const offer={id:'film-example',title:'School-day essentials',product:'example',rateBps:300,budgetCents:50000,reservedCents:150,endsAt:Date.parse('2026-10-19'),terms:'Illustrative offer. Requires funding and provider activation.',treasury:account.address,createdAt:0};
const claim={id:'film-reward',offerId:offer.id,orderId:'EXAMPLE-1842',owner:account.address,cents:150,status:'pending',createdAt:0};
await record('rewards','/rewards',6,async p=>{await p.route('**/api/family-tools',async r=>{const response=await r.fetch();await r.fulfill({response,json:{...await response.json(),offers:[offer],claims:[claim],rewardReady:true}});});await p.route('**/api/family-tools/public',async r=>{const response=await r.fetch();await r.fulfill({response,json:{...await response.json(),offers:[offer],rewardReady:true}});});await p.route('**/api/family-tools/rewards/film-reward/confirm',async r=>{claim.status='confirmed';await r.fulfill({json:{ok:true}});});await connect(p);await p.evaluate(()=>scrollTo(0,210));},async p=>{await p.waitForTimeout(1000);await click(p,p.getByRole('button',{name:'Your reward trail',exact:false}));await click(p,p.getByRole('button',{name:/EXAMPLE-/}));await p.waitForTimeout(800);await click(p,p.getByRole('button',{name:'Confirm delivery',exact:false}));await p.getByRole('status').filter({hasText:'Reward confirmed'}).waitFor();});
await record('context','/asset-passports',3,async p=>{await p.getByRole('link',{name:'Explain this asset'}).click();await p.getByText('Explain this Asset Passport',{exact:true}).waitFor();},async p=>{await p.waitForTimeout(2600);});
await browser.close();writeFileSync(`${root}/capture/manifest.json`,JSON.stringify(manifest,null,2));
