import { useState } from 'react';
import type { HarvestRound, HarvestRegistration } from '@sprout/shared';
import { HarvestHeader, harvestRequest, displayAmount } from './ManualHarvestPage';

export function HarvestOperator() {
  const [token,setToken]=useState(''),[authenticated,setAuthenticated]=useState(false),[rounds,setRounds]=useState<HarvestRound[]>([]),[selected,setSelected]=useState<HarvestRound|null>(null),[rows,setRows]=useState<HarvestRegistration[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const call=<T,>(path:string,method='GET',body?:unknown)=>harvestRequest<T>(`/api/harvest/admin/${path}`,{method,headers:{'x-sprout-admin-token':token,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const load=async()=>{const data=await harvestRequest<{rounds:HarvestRound[]}>('/api/harvest');setRounds(data.rounds);};
  const select=async(id:string)=>{const data=await call<{round:HarvestRound;registrations:HarvestRegistration[]}>(`rounds/${id}`);setSelected(data.round);setRows(data.registrations);};
  const run=async(work:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');setMessage('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Operation failed.');if(selected){try{await select(selected.id);}catch{ /* Keep the original operation error. */ }}}finally{setBusy(false);}};
  const create=async(form:HTMLFormElement)=>{
    const data=new FormData(form);const input={title:String(data.get('title')),token:String(data.get('asset')),funder:String(data.get('funder')),budget:String(data.get('budget')),closesAt:new Date(String(data.get('deadline'))).getTime()};
    const result=await call<{round:HarvestRound}>('rounds','POST',input);await load();await select(result.round.id);setMessage('Round published. Holders can now register.');form.reset();
  };
  const exportCsv=async()=>{if(!selected)return;const response=await fetch(`/api/harvest/admin/rounds/${selected.id}/export`,{headers:{'x-sprout-admin-token':token}});if(!response.ok){const data=await response.json();throw new Error(data.error);}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`harvest-${selected.id}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <div className="harvest-root"><HarvestHeader><a href="/harvest">Holder view</a>{authenticated&&<button className="harvest-link" onClick={()=>{setToken('');setAuthenticated(false);setRows([]);setSelected(null);}}>Sign out</button>}</HarvestHeader><main className="harvest-main"><div className="harvest-heading"><h1>The harvest desk.</h1><span className="harvest-preview">Operator access</span></div><p>Publish a budget, close registration, then pay holders from your treasury wallet. This screen never signs or sends transfers.</p>
    {error&&<p className="harvest-error" role="alert">{error}</p>}{message&&<p className="harvest-success" role="status">{message}</p>}
    {!authenticated?<form className="manual-admin-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await call('status');setAuthenticated(true);await load();});}}><label>SPROUT operator token<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} required/></label><div><p>Use the existing server admin token. It stays in memory until you leave or sign out.</p><button className="harvest-button" disabled={busy||!token}>{busy?'Checking…':'Open operator desk'}</button></div></form>:<>
    <section><h2>Publish a round</h2><p>Robinhood Chain only. Use the exact payout token contract and the wallet that will send every payment. Its balance must cover the budget. Publishing announces the budget; it does not reserve or move funds.</p><form className="manual-admin-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;void run(()=>create(form));}}><label>Round title<input name="title" minLength={3} maxLength={80} required placeholder="Harvest · First round"/></label><label>Total payout budget<input name="budget" inputMode="decimal" pattern="[0-9]+(\.[0-9]+)?" required placeholder="Amount in payout tokens"/></label><label>Payout token contract<input name="asset" pattern="0x[0-9a-fA-F]{40}" required placeholder="0x…"/></label><label>Sending treasury wallet<input name="funder" pattern="0x[0-9a-fA-F]{40}" required placeholder="0x…"/></label><label>Registration closes (your local time)<input name="deadline" type="datetime-local" required/></label><div><p>Minimum: 1,000,000 SPROUT at the automatically chosen finalized snapshot. Registered holders share the budget proportionally.</p><button className="harvest-button" disabled={busy}>Publish round</button></div></form></section>
    <section className="manual-admin-list"><h2>Manage rounds</h2><label className="manual-select">Select a round<select value={selected?.id??''} disabled={busy} onChange={e=>{const id=e.target.value;if(id)void run(()=>select(id));}}><option value="">Choose…</option>{rounds.map(r=><option key={r.id} value={r.id}>{r.title} · {r.state}</option>)}</select></label>{selected&&<><h3>{selected.title}</h3><p>{displayAmount(selected.budget,selected.decimals)} {selected.symbol} · {selected.state} · {rows.length} registrations</p><p>Registration deadline: {new Date(selected.closesAt).toLocaleString()} · Snapshot block {selected.snapshotBlock}</p><p>Token <code>{selected.token}</code><br/>Treasury <code>{selected.funder}</code></p><div className="harvest-actions"><button className="harvest-button secondary" disabled={busy} onClick={()=>void run(()=>select(selected.id))}>Refresh</button><button className="harvest-button" disabled={busy||selected.state!=='open'||Date.now()<selected.closesAt} onClick={()=>void run(async()=>{await call(`rounds/${selected.id}/lock`,'POST');await select(selected.id);await load();setMessage('Allocations are locked. Export the list and send the exact payments.');})}>Lock allocations</button><button className="harvest-button secondary" disabled={busy||selected.state!=='locked'} onClick={()=>void run(exportCsv)}>Export unpaid recipients</button><button className="harvest-link" disabled={busy||selected.state!=='open'} onClick={()=>{if(window.confirm('Cancel this round before allocation? Registered holders will see it as cancelled.'))void run(async()=>{await call(`rounds/${selected.id}/cancel`,'POST');await select(selected.id);await load();});}}>Cancel round</button></div>
    <div className="manual-admin-table"><table><thead><tr><th>Wallet</th><th>SPROUT at snapshot</th><th>Allocation</th><th>Payment</th></tr></thead><tbody>{rows.map(r=><tr key={r.address}><td>{r.address}</td><td>{displayAmount(r.balance,selected.holdingDecimals)}</td><td>{r.amount===null?'Pending':`${displayAmount(r.amount,selected.decimals)} ${selected.symbol}`}</td><td>{r.txHash?<a href={`https://robinhoodchain.blockscout.com/tx/${r.txHash}`} target="_blank" rel="noreferrer">Verified ↗</a>:r.pendingTxHash?<><span>Submitted · Not verified</span><br/><button className="harvest-link" disabled={busy} onClick={()=>void run(async()=>{await call(`rounds/${selected.id}/payment`,'POST',{address:r.address,txHash:r.pendingTxHash,logIndex:r.pendingLogIndex});await select(selected.id);setMessage('Payment verified.');})}>Retry verification</button> · <button className="harvest-link" disabled={busy} onClick={()=>{const reason=window.prompt('Confirm the previous transaction failed or was incorrect before clearing it. Explain why (at least 10 characters):');if(reason)void run(async()=>{await call(`rounds/${selected.id}/clear-submission`,'POST',{address:r.address,reason});await select(selected.id);});}}>Clear submission</button></>:'Not paid'}</td></tr>)}</tbody></table></div>
    {selected.state==='locked'&&<><h3>Verify a manual payment</h3><p>After sending the exact allocated amount from the treasury, enter the transaction hash and the ERC-20 Transfer event’s log index. The submission is saved immediately and removed from the unpaid export while verification waits for chain finality. One transfer can settle only one allocation. Do not resend a payment while its transaction is pending.</p><form className="manual-admin-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);void run(async()=>{await call(`rounds/${selected.id}/payment`,'POST',{address:String(data.get('recipient')),txHash:String(data.get('hash')),logIndex:Number(data.get('index'))});await select(selected.id);setMessage('Payment verified. The holder can now see the transaction receipt.');form.reset();});}}><label>Unpaid recipient<select name="recipient" required>{rows.filter(r=>r.amount&&BigInt(r.amount)>0n&&!r.txHash).map(r=><option value={r.address} key={r.address}>{r.address}</option>)}</select></label><label>Transaction hash<input name="hash" pattern="0x[0-9a-fA-F]{64}" required/></label><label>Transfer log index<input name="index" type="number" min="0" step="1" required/></label><button className="harvest-button" disabled={busy||!rows.some(r=>r.amount&&BigInt(r.amount)>0n&&!r.txHash)}>Verify payment</button></form></>}
    </>}</section></>}
    </main></div>;
}
