import { afterEach, describe, expect, test } from 'bun:test';
import { HARVEST_TOKEN, allocateHarvest, type HarvestRound } from '@sprout/shared';
import { createApp } from '../src/app';
import { issueNonce } from '../src/auth';
import type { HarvestRuntime } from '../src/harvest';
import { account, otherAccount, memoryDb, testimonialChain } from './helpers';

const closes:(()=>void)[]=[];afterEach(()=>closes.splice(0).forEach(f=>f()));
function fixture() {
  const db=memoryDb();closes.push(()=>db.close());let time=Date.now(),balance=1000000n*10n**18n,paymentValid=true,holdingDelay:(()=>Promise<void>)|undefined;
  const runtime:HarvestRuntime={snapshot:async()=>({number:100n,hash:'0x'+'ab'.repeat(32)}),asset:async()=>({symbol:'USDTEST',decimals:6,balance:1000000000n}),holdingDecimals:async()=>18,holding:async()=>{await holdingDelay?.();return balance;},verifyPayment:async()=>{if(!paymentValid)throw new Error('unconfirmed');}};
  const app=createApp({db,chain:testimonialChain(),localDemo:false,adminToken:'test-only',harvest:runtime,now:()=>time});
  const admin=(path:string,body?:unknown)=>app.request('/api/harvest/admin/'+path,{method:body===undefined?'GET':'POST',headers:{'x-sprout-admin-token':'test-only','content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const create=async()=>{const res=await admin('rounds',{title:'First harvest',token:HARVEST_TOKEN,funder:otherAccount.address,budget:'100',closesAt:time+3600001});expect(res.status).toBe(201);return (await res.json() as {round:HarvestRound}).round;};
  const credentials=async(id:string,signer=account)=>{const challenge=issueNonce(db,{address:signer.address,purpose:`harvest:${id}`,now:time});return {'x-sprout-address':signer.address,'x-sprout-nonce':challenge.nonce,'x-sprout-signature':await signer.signMessage({message:challenge.message})};};
  const register=async(id:string,signer=account)=>app.request(`/api/harvest/rounds/${id}/register`,{method:'POST',headers:await credentials(id,signer)});
  return {db,app,admin,create,credentials,register,advance:()=>{time+=3600002;},balance:(v:bigint)=>{balance=v;},payment:(v:boolean)=>{paymentValid=v;},delay:(fn:()=>Promise<void>)=>{holdingDelay=fn;}};
}
describe('Manual Harvest',()=>{
  test('integer allocation preserves budget and reports rounding remainder',()=>{const a=allocateHarvest(100n,[{address:'a',balance:'1'},{address:'b',balance:'2'}]);expect(a.allocations.map(v=>v.amount)).toEqual([33n,66n]);expect(a.remainder).toBe(1n);expect(allocateHarvest(100n,[]).remainder).toBe(100n);});
  test('public empty state has no invented money; admin fails closed',async()=>{const f=fixture();expect((await (await f.app.request('/api/harvest')).json()).rounds).toEqual([]);expect((await f.app.request('/api/harvest/admin/status')).status).toBe(401);expect((await f.admin('status')).status).toBe(200);});
  test('rejects insufficient treasury, overprecision and invalid deadline',async()=>{const f=fixture();for(const overrides of [{budget:'1001'},{budget:'0.0000001'},{closesAt:1},{funder:'0x0000000000000000000000000000000000000000'}]){const res=await f.admin('rounds',{title:'Example',token:HARVEST_TOKEN,funder:otherAccount.address,budget:'100',closesAt:Date.now()+7200000,...overrides});expect(res.status).toBe(400);}});
  test('signed registration verifies threshold, blocks replay and is idempotent',async()=>{const f=fixture(),r=await f.create();f.balance(1000000n*10n**18n-1n);expect((await f.register(r.id)).status).toBe(403);f.balance(1000000n*10n**18n);const headers=await f.credentials(r.id);const request=()=>f.app.request(`/api/harvest/rounds/${r.id}/register`,{method:'POST',headers});expect((await request()).status).toBe(200);expect((await request()).status).toBe(401);expect((await f.register(r.id)).status).toBe(200);expect(f.db.query('SELECT * FROM harvest_registrations').all()).toHaveLength(1);});
  test('unsigned and wrong-round messages cannot register',async()=>{const f=fixture(),r=await f.create();expect((await f.app.request(`/api/harvest/rounds/${r.id}/register`,{method:'POST'})).status).toBe(401);const headers=await f.credentials('00000000-0000-4000-8000-000000000000');expect((await f.app.request(`/api/harvest/rounds/${r.id}/register`,{method:'POST',headers})).status).toBe(401);});
  test('registration that crosses deadline does not enter the payout list',async()=>{const f=fixture(),r=await f.create();f.delay(async()=>f.advance());expect((await f.register(r.id)).status).toBe(409);expect(f.db.query('SELECT * FROM harvest_registrations').all()).toHaveLength(0);});
  test('locks immutable pro-rata amounts after deadline and exports only unpaid',async()=>{const f=fixture(),r=await f.create();await f.register(r.id);f.balance(3000000n*10n**18n);await f.register(r.id,otherAccount);expect((await f.admin(`rounds/${r.id}/lock`,{})).status).toBe(409);f.advance();expect((await f.register(r.id)).status).toBe(409);expect((await f.admin(`rounds/${r.id}/lock`,{})).status).toBe(200);const data=await (await f.admin(`rounds/${r.id}`)).json();expect(data.registrations.find((x:any)=>x.address===account.address.toLowerCase()).amount).toBe('25000000');expect(data.registrations.find((x:any)=>x.address===otherAccount.address.toLowerCase()).amount).toBe('75000000');expect((await f.admin(`rounds/${r.id}/lock`,{})).status).toBe(409);expect((await f.admin(`rounds/${r.id}/cancel`,{})).status).toBe(409);expect(await (await f.admin(`rounds/${r.id}/export`)).text()).toContain('25000000');});
  test('failed payment verification never marks paid; duplicate transfer is rejected',async()=>{const f=fixture(),r=await f.create();await f.register(r.id);await f.register(r.id,otherAccount);f.advance();await f.admin(`rounds/${r.id}/lock`,{});const payment={address:account.address,txHash:'0x'+'cd'.repeat(32),logIndex:2};f.payment(false);expect((await f.admin(`rounds/${r.id}/payment`,payment)).status).toBe(503);f.payment(true);expect((await f.admin(`rounds/${r.id}/payment`,payment)).status).toBe(200);expect((await f.admin(`rounds/${r.id}/payment`,payment)).status).toBe(409);expect((await f.admin(`rounds/${r.id}/payment`,{...payment,address:otherAccount.address})).status).toBe(409);const csv=await (await f.admin(`rounds/${r.id}/export`)).text();expect(csv).not.toContain(account.address.toLowerCase());expect(csv).toContain(otherAccount.address.toLowerCase());});
  test('cancelled rounds cannot register or allocate',async()=>{const f=fixture(),r=await f.create();expect((await f.admin(`rounds/${r.id}/cancel`,{})).status).toBe(200);expect((await f.register(r.id)).status).toBe(409);f.advance();expect((await f.admin(`rounds/${r.id}/lock`,{})).status).toBe(409);});
  test('pending submissions are durable, excluded from exports and require audited clearing',async()=>{const f=fixture(),r=await f.create();await f.register(r.id);f.advance();await f.admin(`rounds/${r.id}/lock`,{});f.payment(false);const payment={address:account.address,txHash:'0x'+'ab'.repeat(32),logIndex:0};expect((await f.admin(`rounds/${r.id}/payment`,payment)).status).toBe(503);const view=await (await f.app.request(`/api/harvest/account/${account.address}`)).json();expect(view.registrations[0].pendingTxHash).toBe(payment.txHash);expect(view.registrations[0].txHash).toBeNull();expect(await (await f.admin(`rounds/${r.id}/export`)).text()).not.toContain(account.address.toLowerCase());expect((await f.admin(`rounds/${r.id}/payment`,{...payment,txHash:'0x'+'ef'.repeat(32)})).status).toBe(409);expect((await f.admin(`rounds/${r.id}/clear-submission`,{address:account.address,reason:'x'})).status).toBe(400);expect((await f.admin(`rounds/${r.id}/clear-submission`,{address:account.address,reason:'Operator verified transaction was incorrect.'})).status).toBe(200);expect(await (await f.admin(`rounds/${r.id}/export`)).text()).toContain(account.address.toLowerCase());expect(f.db.query("SELECT * FROM harvest_audit WHERE action='submission-cleared'").all()).toHaveLength(1);});
  test('an announced budget cannot silently reuse another round’s unpaid funds',async()=>{const f=fixture();await f.create();const response=await f.admin('rounds',{title:'Another round',token:HARVEST_TOKEN,funder:otherAccount.address,budget:'1000',closesAt:Date.now()+7200000});expect(response.status).toBe(409);});
});
