import React,{useState,useEffect} from 'react';
import {AbsoluteFill,Audio,Img,staticFile,useCurrentFrame,delayRender,continueRender} from 'remotion';
import {SpendView,SpendCard,type SpendViewProps} from './product/SpendView';
import './film.css';
const C={ink:'#252623',paper:'#fff',shell:'#f3f2ed',olive:'#60774d',muted:'#73766e'};
const clamp=(n:number)=>Math.max(0,Math.min(1,n));const ease=(n:number)=>1-Math.pow(1-clamp(n),4);const at=(t:number,s=0,d=.7)=>ease((t-s)/d);
const products=[['amazon_com-usa','Amazon','Shopping'],['steam-usa','Steam','Gaming'],['nintendo-usa','Nintendo eShop','Gaming'],['spotify-usa','Spotify','Music'],['xbox-usa','Xbox','Gaming'],['bookshop-usa','Barnes & Noble','Books']].map(([id,name,category])=>({id,name,category,country:'US',currency:'USD',values:[10,25,50,100]}));
const nothing=()=>{};const wallet='0x58a162a186438827104f842967ac5bb2e47b42A1',vault='0x93beB6Ddf3706F2d6862541E28180d60dB1Ac947';
function view(screen:SpendViewProps['screen'],t=0):SpendViewProps{
 const order={id:'SP-0926-1842',product:products[1],value:25,status:screen==='receipt'?'delivered':'unpaid',createdAt:0,payment:{address:'0x4879deA36089dAC95f1Bfb474978C0359D040a1c',amount:'25.00',chainId:8453,token:'0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',expiresAt:9999999999999},redemption:{code:'K7PX · 4M2Q · 8R9V',instructions:'Open your Steam account and choose Redeem a Steam Gift Card or Wallet Code.'}} as any;
 return {catalog:{enabled:true,products,perOrderLimit:100,dailyLimit:200,country:'US'},screen,products,selected:products[1],value:t<1.25?10:25,search:'',category:'All',wallet,vault,vaults:[{id:vault}],approved:t>3,busy:false,error:'',order:screen==='review'||screen==='shop'?null:order,orders:[order],revealed:t>2.3,copied:t>4.1,sent:false,onScreen:nothing,onSelect:nothing,onValue:nothing,onSearch:nothing,onCategory:nothing,onConnect:nothing,onVault:nothing,onApprove:nothing,onCheckout:nothing,onPay:nothing,onRefresh:nothing,onReveal:nothing,onCopy:nothing,onOrder:nothing,assetUrl:p=>staticFile(p.slice(1))};
}
function Mark({size=35}:{size?:number}){return <div style={{display:'flex',alignItems:'center',gap:12,fontFamily:'Satoshi',fontWeight:750,fontSize:size,letterSpacing:-1.5}}><Img src={staticFile('brand/sprout-logo.png')} style={{width:size*1.2,height:size*1.2,borderRadius:8}}/>SPROUT <span style={{fontFamily:'Georgia',fontStyle:'italic',fontWeight:400,color:C.olive,marginLeft:10}}>spend</span></div>}
function Rise({t,children}:{t:number;children:React.ReactNode}){return <div style={{overflow:'hidden',paddingBottom:14,marginBottom:-14}}><div style={{transform:`translateY(${(1-at(t))*110}%)`}}>{children}</div></div>}
function Cursor({x,y,click=false}:{x:number;y:number;click?:boolean}){return <div style={{position:'absolute',left:x,top:y,zIndex:5,transform:`scale(${click?.88:1})`}}>{click&&<div style={{position:'absolute',width:58,height:58,borderRadius:'50%',background:'#60774d25',border:'2px solid #60774d55',left:-20,top:-15}}/>}<svg width="32" height="38" viewBox="0 0 28 35"><path d="M2 2L25 22L15 23L10 33L2 2Z" fill="#252623" stroke="#fff" strokeWidth="2"/></svg></div>}
function Website({screen,t,scale=1,x=0,y=0}:{screen:SpendViewProps['screen'];t:number;scale?:number;x?:number;y?:number}){return <div className="film-site" style={{position:'absolute',width:1440,left:x,top:y,transformOrigin:'0 0',transform:`scale(${scale})`,borderRadius:18,overflow:'hidden',boxShadow:'0 25px 90px #28312215',border:'1px solid #e2e5dc'}}><SpendView {...view(screen,t)}/></div>}
export function SpendFilm(){const [ready]=useState(()=>delayRender('Brand fonts'));useEffect(()=>{document.fonts.load('500 24px Satoshi').then(()=>continueRender(ready));},[ready]);const t=useCurrentFrame()/30;let scene;
 if(t<3){scene=<AbsoluteFill style={{background:C.paper,padding:'78px 115px'}}><Mark size={39}/><div style={{position:'absolute',left:115,top:305,fontFamily:'Georgia',fontSize:117,lineHeight:1.04,letterSpacing:-5}}><Rise t={t}>A little saved.</Rise><Rise t={t-.18}><em style={{color:C.olive}}>A little enjoyed.</em></Rise></div><div style={{position:'absolute',right:90,top:190,width:575,height:650}}><Img src={staticFile('art/harvest-bouquet.png')} style={{width:'100%',height:'100%',objectFit:'contain',transform:`scale(${.85+.15*at(t,.1,1.2)}) rotate(${-5+4*at(t,.1,1.2)}deg)`}}/><div style={{position:'absolute',left:20,top:240,width:440,transform:`translateY(${(1-at(t,.35))*400}px) rotate(-9deg)`}}><SpendCard name="Good things, together." tone={0}/></div></div><p style={{position:'absolute',left:120,bottom:115,fontSize:27,color:C.muted,opacity:at(t,.6)}}>Introducing Sprout Spend.</p></AbsoluteFill>}
 else if(t<9){const s=t-3;const scroll=520*at(s,2,1.2);scene=<AbsoluteFill style={{background:C.shell}}><Website screen="shop" t={s} scale={1.18} x={110} y={55-scroll}/><Cursor x={1250-280*at(s,2.8,1)} y={650+135*at(s,2.8,1)} click={s>4.3&&s<4.65}/><div className="film-caption" style={{opacity:at(s,.3)}}>Find their next little adventure.</div></AbsoluteFill>}
 else if(t<15){const s=t-9;const z=at(s,1.8,1);scene=<AbsoluteFill style={{background:C.shell}}><Website screen="review" t={s} scale={1.1+.25*z} x={165-195*z} y={45-450*z}/><Cursor x={1170-130*at(s,2.2,.6)+260*at(s,4.1,.6)} y={560+230*at(s,2.2,.6)+75*at(s,4.1,.6)} click={(s>1.2&&s<1.5)||(s>3&&s<3.4)||(s>4.8&&s<5.1)}/><div className="film-caption">Choose an amount. Give your approval.</div></AbsoluteFill>}
 else if(t<21){const s=t-15;scene=<AbsoluteFill style={{background:C.shell}}><Website screen="payment" t={s} scale={1.25} x={55} y={-95}/><Cursor x={1470} y={795} click={s>3.5&&s<3.9}/><div className="film-caption">Review the quote. Pay through Sprout.</div></AbsoluteFill>}
 else if(t<27){const s=t-21;scene=<AbsoluteFill style={{background:C.shell}}><Website screen="receipt" t={s} scale={1.24+.025*at(s,0,5)} x={50} y={-70}/><Cursor x={1150+180*at(s,3.5,.5)} y={760+168*at(s,3.5,.5)} click={(s>2.3&&s<2.6)||(s>4.1&&s<4.4)}/><div className="film-caption">Delivered here. Yours to reveal.</div></AbsoluteFill>}
 else {const s=t-27;scene=<AbsoluteFill style={{background:C.paper}}><div style={{position:'absolute',left:120,top:85}}><Mark size={40}/></div><div style={{position:'absolute',left:120,top:310,fontFamily:'Georgia',fontSize:116,letterSpacing:-4.8,lineHeight:1.06}}><Rise t={s}>Little choices.</Rise><Rise t={s-.1}><em style={{color:C.olive}}>Bigger smiles.</em></Rise></div><div style={{position:'absolute',right:90,top:155,width:650,height:730}}><Img src={staticFile('art/harvest-bouquet.png')} style={{width:'100%',height:'100%',objectFit:'contain',transform:`rotate(${-5+5*at(s,0,1.3)}deg)`}}/></div><div style={{position:'absolute',left:130,bottom:130,fontSize:28,color:C.olive,opacity:at(s,.35)}}>sproutfy.tech/spend <span style={{marginLeft:25}}>↗</span></div></AbsoluteFill>}
 return <AbsoluteFill style={{color:C.ink,fontFamily:'Satoshi'}}><Audio src={staticFile('audio/score.wav')} volume={.8}/>{scene}</AbsoluteFill>;
}
