import { ArrowRight, BookOpen, ChevronRight, ExternalLink, Leaf, Printer, ShieldCheck, Sparkles } from 'lucide-react';
import type { ReactNode } from 'react';

export type KnowledgePageKind = 'docs' | 'whitepaper' | 'guide';

type Section = { id: string; eyebrow?: string; title: string; body: ReactNode };

const links = [
  ['/docs', 'Docs'], ['/whitepaper', 'Whitepaper'], ['/guide', 'Guide'], ['/settings', 'Settings'],
  ['/test/', 'Sample mode'], ['/dashboard', 'Dashboard'],
] as const;

function Code({ children }: { children: ReactNode }) { return <code className="knowledge-code">{children}</code>; }
function Callout({ children, tone = 'green' }: { children: ReactNode; tone?: 'green' | 'orange' }) { return <aside className={`knowledge-callout knowledge-callout--${tone}`}>{children}</aside>; }

const docsSections: Section[] = [
  { id: 'overview', eyebrow: 'Developer docs', title: 'A family vault with a clear handover', body: <><p>Sprout is a web app for planting a vault for a child, funding it with admitted tokens, scheduling investments, sharing a gift link, and handing control to the beneficiary at a fixed on-chain timestamp.</p><p>The browser is React + Vite and uses <Code>viem</Code> for wallet and contract calls. The API is Bun + Hono with <Code>bun:sqlite</Code>; it indexes chain events and serves indexed API views for the dashboard.</p></> },
  { id: 'flow', eyebrow: 'Function overview', title: 'The path through the system', body: <><div className="knowledge-steps"><div><b>01</b><span>Plant</span><small>The factory creates a vault with a beneficiary, settlement token, asset weights, venues, and graduation timestamp.</small></div><div><b>02</b><span>Fund</span><small>Supported tokens can be deposited into the vault. A wallet signature is required for live writes.</small></div><div><b>03</b><span>Grow</span><small>A parent can schedule investments; gifts add funds and chores reserve rewards within the vault.</small></div><div><b>04</b><span>Graduate</span><small>At the immutable timestamp, parent permissions end and the beneficiary can withdraw.</small></div></div></> },
  { id: 'contracts', eyebrow: 'Contracts', title: 'Factory, vault, and venue boundaries', body: <><p><Code>SproutFactory</Code> admits the configured assets and venues and creates vaults. <Code>SproutVault</Code> stores the parent, beneficiary, settlement token, allocation weights, schedule, milestones, gifts, and graduation state.</p><p>Investment execution calls an admitted venue with minimum outputs computed from a quote. The adapter and feeds have preconditions: a venue must be configured, quotes must be available, and a feed must be readable and fresh. A stale or invalid price fails closed.</p></> },
  { id: 'backend', eyebrow: 'Backend', title: 'Indexing is a read model, not the source of truth', body: <><p>The Bun server stores sprouts, gifts, gift payments, milestones, jobs, chain events, valuation snapshots, and keeper transactions in SQLite. The indexer reconciles on-chain state into that database so the API can answer indexed dashboard queries.</p><p>Balances, roles, permissions, allocations, schedules, and graduation are enforced by contracts. Device-local nicknames and chore titles are UI conveniences; the app explicitly says they stay on the current device.</p></> },
  { id: 'automation', eyebrow: 'Jobs', title: 'Weekly plans depend on an available keeper', body: <><p>A recurring plan records an amount and period. The server can run due jobs only when a keeper signer and a complete gas budget are configured. When automation is unavailable, the UI keeps the schedule unchanged and reports that it cannot run.</p><p>Keeper execution has receipt reconciliation, a chain-and-signer lock, nonce tracking, and fee accounting. A configured job is not evidence that a trade happened.</p></> },
  { id: 'references', eyebrow: 'References', title: 'Read the source alongside the interface', body: <><p>Start with the repository README, then inspect <Code>contracts/</Code>, <Code>server/src/indexer.ts</Code>, <Code>server/src/jobs.ts</Code>, <Code>shared/src/abis.ts</Code>, and <Code>web/src/App.tsx</Code>. The generated ABI is the contract call surface used by the app.</p><p>For stable primary references, see <a href="https://viem.sh/" target="_blank" rel="noreferrer">viem <ExternalLink size={13} /></a>, <a href="https://vite.dev/guide/" target="_blank" rel="noreferrer">Vite <ExternalLink size={13} /></a>, and <a href="https://docs.soliditylang.org/" target="_blank" rel="noreferrer">Solidity <ExternalLink size={13} /></a>.</p></> },
];

const whitepaperSections: Section[] = [
  { id: 'abstract', eyebrow: 'Technical draft · v0.1 · 2026-09-14', title: 'Sprout: a family vault with an on-chain graduation boundary', body: <><p>Sprout combines a contract-controlled vault with a small indexed web service. A parent creates a vault for a beneficiary, chooses admitted assets and weights, funds it, and may schedule investments. Gifts and approved milestone rewards use the same vault. At a fixed timestamp, parent control ends.</p><Callout tone="orange"><b>Status:</b> This is a technical draft describing the current repository design. It is not a market forecast, product certification, or statement about investment returns.</Callout></> },
  { id: 'model', eyebrow: 'System model', title: 'One vault, distinct actors', body: <><p>The parent is the creator and controller before graduation. The beneficiary is named at creation and receives control after graduation. A gifter can pay a private gift link for a fixed vault; the link does not grant withdrawal access.</p><p>The contract is the authority for balances and permissions. The API authenticates wallet-originated requests, verifies transaction receipts, and exposes indexed records and read-only chain snapshots.</p></> },
  { id: 'state', eyebrow: 'State transitions', title: 'Planting, investing, and graduating', body: <><ul><li><b>Plant:</b> the factory creates a vault with immutable admission rules and a graduation timestamp.</li><li><b>Fund:</b> admitted settlement or stock tokens move into the vault after the relevant wallet approval.</li><li><b>Schedule:</b> a parent records a recurring investment plan; a keeper may execute due work when configured.</li><li><b>Graduate:</b> after the timestamp, parent actions stop and withdrawal is available to the beneficiary.</li></ul><p>The timestamp is fixed at planting and the final handover is irreversible.</p></> },
  { id: 'pricing', eyebrow: 'Execution constraints', title: 'Quotes, feeds, and fail-closed behavior', body: <><p>Before an investment, the server asks the configured venue for a quote and derives minimum outputs. Stock-token valuation reads a configured price feed and rejects paused, invalid, non-positive, or stale rounds. If a holding has no trustworthy price, the total is unknown rather than invented.</p><p>This design makes preconditions visible: a configured venue, readable assets, fresh prices, a working RPC, and a funded keeper are all separate dependencies.</p></> },
  { id: 'boundaries', eyebrow: 'Scope', title: 'What this design does not establish', body: <><p>The repository does not establish fees, certifications, audits, asset backing, legal availability, guaranteed earnings, or universal liquidity. Mainnet and local demo configurations have different capabilities; automatic investing can be disabled when the keeper key or gas budget is absent.</p></> },
];

const guideSections: Section[] = [
  { id: 'first-sprout', eyebrow: 'Start here', title: 'Plant your first sprout', body: <><ol><li>Open <a href="/dashboard">Dashboard</a> and connect a wallet.</li><li>Choose “Plant a sprout”, enter a nickname and beneficiary wallet, select the asset allocation, and choose a future graduation date.</li><li>Review the immutable handover details, then sign the transaction in your wallet.</li></ol><p>The nickname is stored on this device. The beneficiary wallet is the address that receives control at graduation.</p></> },
  { id: 'sample', eyebrow: 'Look around', title: 'Try sample mode first', body: <><p><a href="/test/">Sample mode</a> opens a prepared family wallet with sample balances. It uses no wallet, vault, or live data and does not sign transactions. The dashboard preview is useful for learning the layout before connecting.</p></> },
  { id: 'weekly', eyebrow: 'Build a rhythm', title: 'Set up a weekly investment', body: <><p>From a live sprout, open the weekly plan, choose a settlement amount and period, and sign the schedule transaction. A keeper must be configured for the plan to execute automatically. You can pause or edit future contributions when the UI reports the chain is ready.</p></> },
  { id: 'gifts', eyebrow: 'Family contributions', title: 'Share a gift link', body: <><p>In Gifts, create a link and choose its accepted assets. Send the link to family or friends; they connect a wallet, approve the token, and pay the fixed vault. A gift payment adds funds but never grants withdrawal access.</p></> },
  { id: 'chores', eyebrow: 'Everyday ownership', title: 'Turn a chore into a reward', body: <><p>A parent creates a chore with a token amount already held in the vault; the amount is reserved against the vault balance. When the unlock time is due, the parent releases it into the beneficiary allowance bucket. The beneficiary then claims the allowance. Open Chores &amp; rewards to see created, released, and cancelled milestones.</p></> },
  { id: 'appearance', eyebrow: 'Make it yours', title: 'Set your appearance', body: <><p>Open <a href="/settings">Settings</a> to choose the garden’s appearance, including System behavior. The preference is saved on this device, so it follows this browser rather than changing anyone else’s workspace.</p></> },
  { id: 'growing-up', eyebrow: 'The handover', title: 'Growing up', body: <><p>The graduation date is fixed when the sprout is planted. Before it, parent controls apply. Once the timestamp passes, parent powers stop, the beneficiary can take over, and withdrawal unlocks. The handover cannot be undone.</p><Callout>Keep the beneficiary wallet safe. Sprout cannot recover a lost wallet or reverse a completed graduation.</Callout></> },
  { id: 'tips', eyebrow: 'Small habits', title: 'Tips for using Sprout', body: <><ul><li>Try the sample preview before your first signature.</li><li>Read the supported assets and current price status in the dashboard.</li><li>Keep your wallet connected while checking a transaction result.</li><li>Treat the chart as a record of available snapshots, not a promise of growth.</li><li>Pause a weekly plan when your family’s budget or schedule changes.</li></ul></> },
];

const pageData: Record<KnowledgePageKind, { label: string; title: string; intro: string; sections: Section[] }> = {
  docs: { label: 'Developer docs', title: 'How the garden works', intro: 'A readable map of the contracts, backend, and browser app behind Sprout.', sections: docsSections },
  whitepaper: { label: 'Technical draft', title: 'A small system for growing ownership', intro: 'The current design, its boundaries, and the conditions that make each action possible.', sections: whitepaperSections },
  guide: { label: 'Family guide', title: 'Start small. Grow together.', intro: 'A straightforward path through the real Sprout experience, from sample mode to graduation.', sections: guideSections },
};

export function KnowledgePage({ page }: { page: KnowledgePageKind }) {
  const data = pageData[page];
  return <div className={`knowledge knowledge-root knowledge--${page}`}>
    <header className="knowledge-topbar"><a className="knowledge-brand" href="/"><span className="knowledge-brand-mark"><img src="/brand/sprout-logo.png" alt="" /></span><span>SPROUT</span></a><nav aria-label="Knowledge navigation">{links.map(([href, label]) => <a className={href === `/${page}` ? 'is-current' : ''} href={href} key={href}>{label}</a>)}</nav><button className="knowledge-print" onClick={() => window.print()}><Printer size={16} /> Print</button></header>
    <div className="knowledge-layout"><aside className="knowledge-sidebar"><div className="knowledge-side-kicker"><Leaf size={16} /> Knowledge garden</div><p>Find your way around the little system.</p><nav aria-label="On this page">{data.sections.map((section) => <a href={`#${section.id}`} key={section.id}><ChevronRight size={13} />{section.title}</a>)}</nav><div className="knowledge-side-links"><a href="/dashboard"><Sparkles size={14} /> Open dashboard</a><a href="/settings"><ShieldCheck size={14} /> Settings</a></div></aside>
      <main className="knowledge-main"><div className="knowledge-hero"><span className="knowledge-eyebrow">{data.label}</span><h1>{data.title}</h1><p>{data.intro}</p><div className="knowledge-hero-links"><a href="/dashboard">Open Sprout <ArrowRight size={15} /></a><a href="/test/">See sample mode <ArrowRight size={15} /></a></div></div><div className="knowledge-content">{data.sections.map((section) => <section className="knowledge-section" id={section.id} key={section.id}><span className="knowledge-eyebrow">{section.eyebrow}</span><h2>{section.title}</h2>{section.body}</section>)}</div><footer className="knowledge-footer"><BookOpen size={17} /><span>Sprout docs · technical draft v0.1 · 2026-09-14</span><a href="/dashboard">Go to dashboard <ArrowRight size={14} /></a></footer></main></div>
  </div>;
}
