import { ArrowRight, BookOpen, ChevronRight, ExternalLink, Leaf, Printer, ShieldCheck, Sparkles } from 'lucide-react';
import type { ReactNode } from 'react';
import { useAutomationEnabled } from '../automationStatus';
import { betaPoints } from '../components/BetaNotice';

/** The beta risk list, with the automation line taken from the server. */
function RiskList() {
  const enabled = useAutomationEnabled();
  return <ul>{betaPoints(enabled).map((point) => <li key={point}>{point}</li>)}</ul>;
}

export type KnowledgePageKind = 'docs' | 'whitepaper' | 'guide' | 'faq';

type Section = { id: string; eyebrow?: string; title: string; body: ReactNode };

const links = [
  ['/faq', 'FAQ'], ['/docs', 'Docs'], ['/whitepaper', 'Whitepaper'], ['/guide', 'Guide'], ['/settings', 'Settings'],
  ['/test/', 'Sample mode'], ['/dashboard', 'Dashboard'],
] as const;

/** Reports the server's actual automation status instead of a fixed claim. */
function AutomationStatus() {
  const enabled = useAutomationEnabled();
  if (enabled === null) return <p>A weekly plan buys automatically when the service is running automatic purchases; otherwise, run each week’s purchase with Invest now.</p>;
  return enabled
    ? <p>Weekly plans run automatically: once a week the service buys the mix for you, as long as prices are fresh and the sprout has the money. You can still use Invest now at any time.</p>
    : <p>Automatic weekly investing is switched off right now. You can still keep a weekly plan and run each week’s purchase with Invest now.</p>;
}

function Code({ children }: { children: ReactNode }) { return <code className="knowledge-code">{children}</code>; }
/** What a family needs to reach a sprout without this website (docs/EXIT-WITHOUT-SPROUT.md). */
const EXIT_TOKENS: Array<{ symbol: string; address: string; decimals: number; example: string }> = [
  { symbol: 'USDG', address: '0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168', decimals: 6, example: '$5 is 5000000' },
  { symbol: 'AAPL', address: '0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9', decimals: 18, example: '0.5 is 500000000000000000' },
  { symbol: 'NVDA', address: '0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC', decimals: 18, example: '' },
  { symbol: 'MSFT', address: '0xe93237C50D904957Cf27E7B1133b510C669c2e74', decimals: 18, example: '' },
  { symbol: 'SPY', address: '0x117cc2133c37B721F49dE2A7a74833232B3B4C0C', decimals: 18, example: '' },
];
const SOURCIFY_VAULT = 'https://repo.sourcify.dev/4663/0x789ca950BAE92f4c18f5eBf776d54d85a0fF9A59';
function ExitTokens() {
  return <ul>{EXIT_TOKENS.map((t) => <li key={t.symbol}><b>{t.symbol}</b> <Code>{t.address}</Code>, {t.decimals} decimals{t.example ? ` (${t.example})` : ''}</li>)}</ul>;
}

function Callout({ children, tone = 'green' }: { children: ReactNode; tone?: 'green' | 'orange' }) { return <aside className={`knowledge-callout knowledge-callout--${tone}`}>{children}</aside>; }

const docsSections: Section[] = [
  { id: 'overview', eyebrow: 'Developer docs', title: 'A family vault with a clear handover', body: <><p>Sprout is a web app for planting a vault for a child, funding it with admitted tokens, scheduling investments, sharing a gift link, and handing control to the beneficiary at a fixed on-chain timestamp.</p><p>The browser is React + Vite and uses <Code>viem</Code> for wallet and contract calls. The API is Bun + Hono with <Code>bun:sqlite</Code>; it indexes chain events and serves indexed API views for the dashboard.</p></> },
  { id: 'flow', eyebrow: 'Function overview', title: 'The path through the system', body: <><div className="knowledge-steps"><div><b>01</b><span>Plant</span><small>The factory creates a vault with a beneficiary, settlement token, asset weights, venues, and graduation timestamp.</small></div><div><b>02</b><span>Fund</span><small>Supported tokens can be deposited into the vault. A wallet signature is required for live writes.</small></div><div><b>03</b><span>Grow</span><small>A parent can schedule investments; gifts add funds and chores reserve rewards within the vault.</small></div><div><b>04</b><span>Graduate</span><small>At the immutable timestamp, parent permissions end and the beneficiary can withdraw.</small></div></div></> },
  { id: 'contracts', eyebrow: 'Contracts', title: 'Factory, vault, and venue boundaries', body: <><p><Code>SproutFactory</Code> admits the configured assets and venues and creates vaults. <Code>SproutVault</Code> stores the parent, beneficiary, settlement token, allocation weights, schedule, milestones, gifts, and graduation state.</p><p>Investment execution calls an admitted venue with minimum outputs computed from a quote. The adapter and feeds have preconditions: a venue must be configured, quotes must be available, and a feed must be readable and fresh. A stale or invalid price fails closed.</p></> },
  { id: 'exit', eyebrow: 'Without the app', title: 'Calling a sprout directly', body: <><p>The web app and server are optional. Every sprout is a minimal-proxy copy of <Code>SproutVault</Code>, verified on <a href={SOURCIFY_VAULT} target="_blank" rel="noopener noreferrer">Sourcify</a>, with no owner, admin key, pause or upgrade path. These calls are the whole way out, and any contract tool can make them with <a href="/sprout-vault.abi.json">sprout-vault.abi.json</a>:</p><ul><li><Code>createMilestone(bytes32 id, address token, uint256 amount, uint64 unlockTime)</Code> and <Code>releaseMilestone(bytes32 id)</Code>: parent only, before <Code>graduationTimestamp</Code>. The token must be the settlement token or in <Code>assets()</Code>, and the amount at most the balance less <Code>allowanceBucket</Code> and <Code>totalEarmarked</Code>.</li><li><Code>claimAllowance(address token, uint256 amount)</Code>: beneficiary only, any time, up to <Code>allowanceBucket(token)</Code>; pays the beneficiary.</li><li><Code>withdraw(address token, uint256 amount, address to)</Code>: beneficiary only, from <Code>graduationTimestamp</Code>; pays any address.</li></ul><p>Nothing else moves tokens out except purchases through the factory-admitted venue, whose output stays in the vault. Token addresses and units:</p><ExitTokens /><p><Code>bun run fork:exit</Code> runs this whole path on a local fork against the real factory and every live sprout, with no server. The family-facing steps are in the <a href="/guide#without-sprout">guide</a>.</p></> },
  { id: 'backend', eyebrow: 'Backend', title: 'Indexing is a read model, not the source of truth', body: <><p>The Bun server stores sprouts, gifts, gift payments, milestones, jobs, chain events, valuation snapshots, and keeper transactions in SQLite. The indexer reconciles on-chain state into that database so the API can answer indexed dashboard queries.</p><p>Balances, roles, permissions, allocations, schedules, and graduation are enforced by contracts. Device-local nicknames and chore titles are UI conveniences; the app explicitly says they stay on the current device.</p></> },
  { id: 'automation', eyebrow: 'Jobs', title: 'Weekly plans depend on an available keeper', body: <><p>A recurring plan records an amount and period. The server can run due jobs only when a keeper signer and a complete gas budget are configured. When automation is unavailable, the UI keeps the schedule unchanged and reports that it cannot run.</p><p>Keeper execution has receipt reconciliation, a chain-and-signer lock, nonce tracking, and fee accounting. A configured job is not evidence that a trade happened.</p></> },
  { id: 'references', eyebrow: 'References', title: 'Read the source alongside the interface', body: <><p>Start with the repository README, then inspect <Code>contracts/</Code>, <Code>server/src/indexer.ts</Code>, <Code>server/src/jobs.ts</Code>, <Code>shared/src/abis.ts</Code>, and <Code>web/src/App.tsx</Code>. The generated ABI is the contract call surface used by the app.</p><p>For stable primary references, see <a href="https://viem.sh/" target="_blank" rel="noreferrer">viem <ExternalLink size={13} /></a>, <a href="https://vite.dev/guide/" target="_blank" rel="noreferrer">Vite <ExternalLink size={13} /></a>, and <a href="https://docs.soliditylang.org/" target="_blank" rel="noreferrer">Solidity <ExternalLink size={13} /></a>.</p></> },
];

const whitepaperSections: Section[] = [
  { id: 'abstract', eyebrow: 'Technical draft · v0.1 · 2026-09-14', title: 'Sprout: a family vault with an on-chain graduation boundary', body: <><p>Sprout combines a contract-controlled vault with a small indexed web service. A parent creates a vault for a beneficiary, chooses admitted assets and weights, funds it, and may schedule investments. Gifts and approved milestone rewards use the same vault. At a fixed timestamp, parent control ends.</p><Callout tone="orange"><b>Status:</b> This is a technical draft describing the current repository design. It is not a market forecast, product certification, or statement about investment returns.</Callout></> },
  { id: 'model', eyebrow: 'System model', title: 'One vault, distinct actors', body: <><p>The parent is the creator and controller before graduation. The beneficiary is named at creation and receives control after graduation. A gifter can pay a private gift link for a fixed vault; the link does not grant withdrawal access.</p><p>The contract is the authority for balances and permissions. The API authenticates wallet-originated requests, verifies transaction receipts, and exposes indexed records and read-only chain snapshots.</p></> },
  { id: 'state', eyebrow: 'State transitions', title: 'Planting, investing, and graduating', body: <><ul><li><b>Plant:</b> the factory creates a vault with immutable admission rules and a graduation timestamp.</li><li><b>Fund:</b> admitted settlement or stock tokens move into the vault after the relevant wallet approval.</li><li><b>Schedule:</b> a parent records a recurring investment plan; a keeper may execute due work when configured.</li><li><b>Graduate:</b> after the timestamp, parent actions stop and withdrawal is available to the beneficiary.</li></ul><p>The timestamp is fixed at planting and the final handover is irreversible.</p></> },
  { id: 'pricing', eyebrow: 'Execution constraints', title: 'Quotes, feeds, and fail-closed behavior', body: <><p>Before an investment, the server asks the configured venue for a quote and derives minimum outputs. Stock-token valuation reads a configured price feed and rejects paused, invalid, non-positive, or stale rounds. If a holding has no trustworthy price, the total is unknown rather than invented.</p><p>This design makes preconditions visible: a configured venue, readable assets, fresh prices, a working RPC, and a funded keeper are all separate dependencies.</p></> },
  { id: 'boundaries', eyebrow: 'Scope', title: 'What this design does not establish', body: <><p>The repository does not establish fees, certifications, audits, asset backing, legal availability, guaranteed earnings, or universal liquidity. Mainnet and local demo configurations have different capabilities; automatic investing can be disabled when the keeper key or gas budget is absent.</p></> },
];

const guideSections: Section[] = [
  { id: 'first-sprout', eyebrow: 'Start here', title: 'Plant your first sprout', body: <><ol><li>Open <a href="/dashboard">Dashboard</a> and connect a wallet.</li><li>Choose “Plant a sprout”, enter a nickname and beneficiary wallet, select the asset allocation, and choose a future graduation date.</li><li>Review the immutable handover details, then sign the transaction in your wallet.</li></ol><p>The nickname is stored on this device. The beneficiary wallet is the address that receives control at graduation.</p></> },
  { id: 'sample', eyebrow: 'Look around', title: 'Try sample mode first', body: <><p><a href="/test/">Sample mode</a> opens a prepared family wallet with sample balances. It uses no wallet, vault, or live data and does not sign transactions. The dashboard preview is useful for learning the layout before connecting.</p></> },
  { id: 'weekly', eyebrow: 'Build a rhythm', title: 'Set up a weekly investment', body: <><p>From a live sprout, open the weekly plan, choose a settlement amount and period, and sign the schedule transaction. A keeper must be configured for the plan to execute automatically. You can pause or edit future contributions when the UI reports the chain is ready.</p></> },
  { id: 'gifts', eyebrow: 'Family contributions', title: 'Share a gift link', body: <><p>In Gifts, create a link and choose its accepted assets. Send the link to family or friends; they connect a wallet, approve the token, and pay the fixed vault. A gift payment adds funds but never grants withdrawal access.</p></> },
  { id: 'chores', eyebrow: 'Everyday ownership', title: 'Turn a chore into a reward', body: <><p>A parent creates a chore with a token amount already held in the vault; the amount is reserved against the vault balance. When the unlock time is due, the parent releases it into the beneficiary allowance bucket. The beneficiary then claims the allowance. Open Chores &amp; rewards to see created, released, and cancelled milestones.</p></> },
  { id: 'appearance', eyebrow: 'Make it yours', title: 'Set your appearance', body: <><p>Open <a href="/settings">Settings</a> to choose the garden’s appearance, including System behavior. The preference is saved on this device, so it follows this browser rather than changing anyone else’s workspace.</p></> },
  { id: 'growing-up', eyebrow: 'The handover', title: 'Growing up', body: <><p>The graduation date is fixed when the sprout is planted. Before it, parent controls apply. Once the timestamp passes, parent powers stop, the beneficiary can take over, and withdrawal unlocks. The handover cannot be undone.</p><Callout>Keep the beneficiary wallet safe. Sprout cannot recover a lost wallet or reverse a completed graduation.</Callout></> },
  { id: 'without-sprout', eyebrow: 'Just in case', title: 'Taking money out without Sprout', body: <><p>This website is only a window onto your sprout. The money lives in the sprout’s own contract on Robinhood Chain, so if Sprout ever shuts down, it stays exactly where it is, and free tools can still reach it. Nobody at Sprout can move it, freeze it or refund it.</p><Callout tone="orange"><b>Save these now, while the site works:</b> your sprout’s address (on the dashboard, open the wallet menu at the top and copy “This sprout”), the file <a href="/sprout-vault.abi.json">sprout-vault.abi.json</a>, and this page. You’ll also need the wallet that planted the sprout and your child’s wallet, each with a little ETH on Robinhood Chain for fees.</Callout><ol><li>Open <a href="https://remix.ethereum.org" target="_blank" rel="noopener noreferrer">remix.ethereum.org</a> in a browser that has your wallet, and switch the wallet to Robinhood Chain.</li><li>Create a file called <Code>SproutVault.abi</Code>, paste the contents of sprout-vault.abi.json into it, and keep it open.</li><li>Open <b>Deploy &amp; run transactions</b>, choose your wallet as the environment (<b>Browser Extension</b> or <b>Injected Provider</b>), paste your sprout’s address in the contract address box, and press <b>Add</b> (or <b>At Address</b>). The sprout’s buttons appear.</li><li><b>Before the graduation date, from the wallet that planted the sprout:</b> press <Code>createMilestone</Code> with an id you haven’t used (for example <Code>0x0000000000000000000000000000000000000000000000000000000000000e01</Code>), the token address, the amount and <Code>0</Code> for the unlock time. Then press <Code>releaseMilestone</Code> with the same id. Releasing everything is how money comes out early.</li><li><b>From your child’s wallet:</b> press <Code>claimAllowance</Code> with the token address and the amount you released. It arrives in your child’s wallet.</li><li><b>On or after the graduation date, from your child’s wallet:</b> press <Code>withdraw</Code> with the token address, the amount and the wallet to send it to. Repeat for each token.</li></ol><p>Amounts are in each token’s smallest unit:</p><ExitTokens /><p>The money can only ever go to your child’s wallet, never back to the parent, which is why that wallet should be one your family can open. If a step isn’t allowed yet, the tool shows an error and nothing is sent. Practise once with a small sprout so you know the steps before you need them. The code every sprout runs, including the same ABI, stays published on <a href={SOURCIFY_VAULT} target="_blank" rel="noopener noreferrer">Sourcify</a> even if this site is gone.</p></> },
  { id: 'tips', eyebrow: 'Small habits', title: 'Tips for using Sprout', body: <><ul><li>Try the sample preview before your first signature.</li><li>Read the supported assets and current price status in the dashboard.</li><li>Keep your wallet connected while checking a transaction result.</li><li>Treat the chart as a record of available snapshots, not a promise of growth.</li><li>Pause a weekly plan when your family’s budget or schedule changes.</li></ul></> },
];

const faqSections: Section[] = [
  { id: 'what', eyebrow: 'The basics', title: 'What is a sprout?', body: <><p>A sprout is a savings vault for a child. It lives on Robinhood Chain as its own smart contract and holds tokens that track Apple, NVIDIA, Microsoft and the S&amp;P 500, in the mix you choose when you plant it. Family can add to it with a gift link, and on the graduation date you pick, it becomes your child’s.</p></> },
  { id: 'custody', eyebrow: 'Safety', title: 'Who holds the money?', body: <><p>The sprout’s own contract does. Sprout the website never has custody and cannot move funds: the server only reads the chain to show balances and history. Every change to a sprout is a transaction signed in your wallet.</p><Callout tone="orange"><b>Sprout is in beta.</b> The contracts have not been independently audited. Mainnet transactions use real funds and cannot be reversed, so only put in what you are prepared to lose.</Callout></> },
  { id: 'risks', eyebrow: 'Safety', title: 'What are the risks?', body: <><p><b>Sprout is in beta, and it moves real money.</b> Only put in what you are prepared to lose.</p><RiskList /></> },
  { id: 'withdraw', eyebrow: 'Getting money out', title: 'Can I take money out early?', body: <><p>No. Nobody can withdraw from a sprout before its graduation date, including the parent who planted it. That is the point: it works like a trust, not a checking account.</p><p>The one way value leaves early is a chore reward: you set aside an amount, approve it when the chore is done, and your child claims it to their wallet. On the graduation date, your child’s wallet can withdraw everything.</p></> },
  { id: 'date', eyebrow: 'Getting money out', title: 'Can the graduation date or the child’s wallet change?', body: <><p>No. Both are fixed when the sprout is planted. Double-check the child’s wallet address before you sign, and make sure it is a wallet they will be able to use when the date comes. Sprout cannot recover a lost wallet.</p></> },
  { id: 'without-site', eyebrow: 'Getting money out', title: 'How do I get money out if the website is down?', body: <><p>With a free contract tool such as Remix and your sprout’s address. Before the graduation date, the parent releases rewards and your child claims them to their wallet. From the graduation date, your child withdraws everything. The <a href="/guide#without-sprout">family guide</a> has the steps, the token addresses and the units. Save a copy of it, and your sprout’s address, before you need them.</p></> },
  { id: 'funding', eyebrow: 'Adding money', title: 'What do I add money with?', body: <><p>USDG, a dollar stablecoin on Robinhood Chain. It is the token a sprout holds before it is invested. You can also add the supported stock tokens directly. You need a wallet connected to Robinhood Chain, with a little ETH on that chain for network fees.</p></> },
  { id: 'buying', eyebrow: 'Investing', title: 'How does the money turn into stocks?', body: <><p>Money you add arrives as USDG and waits in the sprout until it is invested. Use <b>Invest now</b> on the dashboard to buy your sprout’s mix from your own wallet. Each purchase follows the sprout’s stock mix, and is checked against the market price feed and refused if the trading pool would pay more than 1% less than that price.</p><AutomationStatus /></> },
  { id: 'closed', eyebrow: 'Investing', title: 'Why does a price say it’s unavailable?', body: <><p>Sprout only uses a stock price that has updated within the last day. Over weekends and market holidays the feeds can go quiet, so Sprout shows that value as unavailable and holds off on purchases until prices update, rather than guessing. Invest now tells you when this is why it can’t buy.</p></> },
  { id: 'fees', eyebrow: 'Costs', title: 'What does it cost?', body: <><p>Sprout’s contracts take no fee. You pay the network fee for each transaction you sign (in ETH on Robinhood Chain), and purchases pay the trading pool’s fee, which is part of the price you get.</p></> },
  { id: 'gifts', eyebrow: 'Family', title: 'How do gift links work?', body: <><p>Create a link from the Gifts page and share it. Anyone with the link can add money to that sprout from their own wallet. A gift cannot be taken back, and the link gives no one any control over the sprout.</p></> },
  { id: 'site', eyebrow: 'Safety', title: 'What if Sprout shuts down?', body: <><p>Your sprout keeps working. It is its own contract on Robinhood Chain with no owner or admin key, so nobody at Sprout can move, freeze or refund the money, and nothing about it depends on this website or our server.</p><p>Before the graduation date, money only leaves as rewards the parent releases, which the child claims to their wallet. To take everything out early, release the whole balance as rewards. From the graduation date, the child’s wallet can withdraw everything, to any address.</p><p>Without this website, use any tool that can call a contract, such as Remix, with your sprout’s address (on the dashboard, open the wallet menu at the top and copy “This sprout”). The code every sprout runs is published and verified on <a href="https://repo.sourcify.dev/4663/0x789ca950BAE92f4c18f5eBf776d54d85a0fF9A59" target="_blank" rel="noopener noreferrer">Sourcify</a>. Keep a note of that address, keep the child’s wallet safe, and see <a href="/guide#without-sprout">Taking money out without Sprout</a> for the steps.</p><Callout tone="orange">Some things are outside Sprout’s control: the stock tokens and USDG depend on the companies that issue them, and purchases depend on the trading pools. If the pools stop trading, withdrawals and reward claims still work.</Callout></> },
  { id: 'privacy', eyebrow: 'Privacy', title: 'What do you store about my family?', body: <><p>Nicknames and chore titles stay in your browser. The server stores wallet addresses, vault addresses, the labels you give gift links, and the on-chain events it indexes. Everything except the gift labels is public on the chain anyway. Anyone who knows a vault address can see its balance, like any other on-chain account.</p></> },
  { id: 'eligibility', eyebrow: 'Before you start', title: 'Can I use Sprout?', body: <><p>Robinhood’s stock tokens are not available everywhere. Check that you are allowed to hold them where you live before you plant a sprout. Nothing on this site is financial, tax or legal advice.</p></> },
];

const pageData: Record<KnowledgePageKind, { label: string; title: string; intro: string; sections: Section[] }> = {
  docs: { label: 'Developer docs', title: 'How the garden works', intro: 'A readable map of the contracts, backend, and browser app behind Sprout.', sections: docsSections },
  whitepaper: { label: 'Technical draft', title: 'A small system for growing ownership', intro: 'The current design, its boundaries, and the conditions that make each action possible.', sections: whitepaperSections },
  guide: { label: 'Family guide', title: 'Start small. Grow together.', intro: 'A straightforward path through the real Sprout experience, from sample mode to graduation.', sections: guideSections },
  faq: { label: 'Questions', title: 'Good to know before you start', intro: 'Where the money lives, when it can come out, what it costs, and what beta means.', sections: faqSections },
};

export function KnowledgePage({ page }: { page: KnowledgePageKind }) {
  const data = pageData[page];
  return <div className={`knowledge knowledge-root knowledge--${page}`}>
    <header className="knowledge-topbar"><a className="knowledge-brand" href="/"><span className="knowledge-brand-mark"><img src="/brand/sprout-logo.png" alt="" /></span><span>SPROUT</span></a><nav aria-label="Knowledge navigation">{links.map(([href, label]) => <a className={href === `/${page}` ? 'is-current' : ''} href={href} key={href}>{label}</a>)}</nav><button className="knowledge-print" onClick={() => window.print()}><Printer size={16} /> Print</button></header>
    <div className="knowledge-layout"><aside className="knowledge-sidebar"><div className="knowledge-side-kicker"><Leaf size={16} /> Knowledge garden</div><p>Find your way around the little system.</p><nav aria-label="On this page">{data.sections.map((section) => <a href={`#${section.id}`} key={section.id}><ChevronRight size={13} />{section.title}</a>)}</nav><div className="knowledge-side-links"><a href="/dashboard"><Sparkles size={14} /> Open dashboard</a><a href="/settings"><ShieldCheck size={14} /> Settings</a></div></aside>
      <main className="knowledge-main"><div className="knowledge-hero"><span className="knowledge-eyebrow">{data.label}</span><h1>{data.title}</h1><p>{data.intro}</p><div className="knowledge-hero-links"><a href="/dashboard">Open Sprout <ArrowRight size={15} /></a><a href="/test/">See sample mode <ArrowRight size={15} /></a></div></div><div className="knowledge-content">{data.sections.map((section) => <section className="knowledge-section" id={section.id} key={section.id}><span className="knowledge-eyebrow">{section.eyebrow}</span><h2>{section.title}</h2>{section.body}</section>)}</div><footer className="knowledge-footer"><BookOpen size={17} /><span>Sprout docs · technical draft v0.1 · 2026-09-14</span><a href="/dashboard">Go to dashboard <ArrowRight size={14} /></a></footer></main></div>
  </div>;
}
