import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const root = join(import.meta.dir, '..');
const artifacts = join(root, 'contracts', 'out');
const target = join(root, 'shared', 'src', 'abis.ts');

const contracts = [
  ['sproutFactoryAbi', 'SproutFactory.sol', 'SproutFactory'],
  ['sproutVaultAbi', 'SproutVault.sol', 'SproutVault'],
  ['mockErc20Abi', 'MockERC20.sol', 'MockERC20'],
  ['mockPriceFeedAbi', 'MockPriceFeed.sol', 'MockPriceFeed'],
  ['mockVenueAbi', 'MockVenue.sol', 'MockVenue'],
  ['mockSwapRouterAbi', 'MockSwapRouter.sol', 'MockSwapRouter'],
  ['uniswapV3AdapterAbi', 'UniswapV3Adapter.sol', 'UniswapV3Adapter'],
] as const;

let out = '// Generated by scripts/gen-abis.ts. Do not edit by hand.\n\n';

for (const [exportName, file, name] of contracts) {
  const artifact = JSON.parse(readFileSync(join(artifacts, file, `${name}.json`), 'utf8'));
  out += `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out);
console.log(`wrote ${target}`);
