import { createRequire } from 'node:module';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const require = createRequire(new URL('../shared/package.json', import.meta.url));
const { plonk, wtns } = require('snarkjs');
const { buildPoseidon } = require('circomlibjs');
const hash = await buildPoseidon();
const dir = path.join(root, 'web/public/zk/milestone-v1');
const wasm = path.join(dir, 'milestone.wasm');
const zkey = path.join(dir, 'milestone.zkey');
const vk = JSON.parse(await readFile(path.join(dir, 'verification_key.json'), 'utf8'));
const logger = { info() {}, warn() {}, error() {}, debug() {} };
const id = randomBytes(16).toString('hex');
const witness = {
  balance: '125000',
  salt: BigInt(`0x${randomBytes(31).toString('hex')}`).toString(),
  scope: BigInt(`0x${id}`).toString(),
  threshold: '50000',
};
witness.commitment = hash.F.toObject(
  hash([BigInt(witness.balance), BigInt(witness.salt), BigInt(witness.scope)]),
).toString();
const start = Date.now();
const result = await plonk.fullProve(witness, wasm, zkey, logger, { memorySize: 0 }, { singleThread: true });
assert.equal(await plonk.verify(vk, result.publicSignals, result.proof, logger), true);
assert.deepEqual(result.publicSignals, [witness.commitment, witness.threshold, witness.scope]);
console.log(`Real PLONK proof and verification passed in ${Date.now() - start}ms.`);
for (let i = 0; i < 3; i++) {
  const signals = [...result.publicSignals];
  signals[i] = (BigInt(signals[i]) + 1n).toString();
  assert.equal(await plonk.verify(vk, signals, result.proof, logger), false);
}
assert.equal(await plonk.verify(vk, result.publicSignals, { ...result.proof, eval_a: '0' }, logger), false);
for (const change of [
  { threshold: '125001' },
  { threshold: '0' },
  { balance: '-1' },
  { balance: '18446744073709551616' },
  { threshold: '18446744073709551616' },
  { salt: (1n << 248n).toString() },
  { scope: (1n << 128n).toString() },
  { balance: '125001' },
  { salt: (BigInt(witness.salt) + 1n).toString() },
]) {
  await assert.rejects(wtns.calculate({ ...witness, ...change }, wasm, { type: 'mem' }, { memorySize: 0 }));
}
// Exact equality succeeds: check the boundary using the compiled circuit.
await wtns.calculate({ ...witness, threshold: witness.balance }, wasm, { type: 'mem' }, { memorySize: 0 });
const call = await plonk.exportSolidityCallData(result.proof, result.publicSignals);
const [proofBytes, publicSignals] = JSON.parse(`[${call.replace('][', '],[')}]`);
await mkdir(path.join(root, 'contracts/test/fixtures'), { recursive: true });
await writeFile(
  path.join(root, 'contracts/test/fixtures/PrivateMilestoneProof.sol'),
  `// SPDX-License-Identifier: GPL-3.0\npragma solidity ^0.8.24;\n// Generated by scripts/test-zk.mjs from a synthetic balance. No private witness included.\nlibrary PrivateMilestoneProof {\n function sample() internal pure returns (uint256[24] memory proof, uint256[3] memory signals) {\n proof = [uint256(${proofBytes[0]}), ${proofBytes.slice(1).join(', ')}];\n signals = [uint256(${publicSignals[0]}), ${publicSignals.slice(1).join(', ')}];\n }\n}\n`,
);
console.log(
  'Rejected changed commitment, threshold, scope, proof, insufficient balance, overflow, negative values and wrong salt.',
);
console.log('Exported the valid proof for the Solidity verifier test.');
process.exit(0);
