import React,{useEffect,useState} from 'react';
import {AbsoluteFill,Img,Audio,staticFile,useCurrentFrame,delayRender,continueRender} from 'remotion';
import {ToolsView,type ToolsViewProps,type ToolPage} from './product/ToolsView';
import {assetPassport,type LedgerEntry} from './product/shared';
import './film.css';
const C={paper:'#ffffff',white:'#fff',ink:'#252623',green:'#476249',sage:'#f3f2ed',orange:'#ec793c',line:'#dce3d4',muted:'#717a70'};
const clamp=(x:number)=>Math.max(0,Math.min(1,x)),ease=(x:number)=>1-Math.pow(1-clamp(x),4),at=(t:number,s=0,d=.7)=>ease((t-s)/d);
const noop=()=>{};const wallet='0x3A9215188D0bA58a26B594F11AC056C9920cF210';
const passports=[['AAPL','0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9'],['NVDA','0x8e0092345678901234567890123456789012345678'],['SPY','0x9e0092345678901234567890123456789012345678']].map(([symbol,address])=>assetPassport({symbol,address},4663));
const entries:LedgerEntry[]=[{id:'example-record',date:'2026-09-18T12:00:00Z',kind:'spend',asset:'USDC',quantity:'50',chainId:8453,wallet,usdCents:5000,basisCents:null,feeCents:0,note:'Illustrative family purchase record',source:'manual'},{id:'example-gift',date:'2026-09-16T12:00:00Z',kind:'gift',asset:'USDC',quantity:'25',chainId:8453,wallet,usdCents:2500,basisCents:null,feeCents:0,note:'Illustrative gift',source:'manual'}];
function props(page:ToolPage,t:number):ToolsViewProps{return {page,wallet,busy:false,error:'',notice:page==='tax'&&t>3?'Record saved.':page==='investing'&&t>3?'Your family plan is saved. No account was opened or trade placed.':'',data:{entries:entries.map((e,i)=>i===0&&t>3?{...e,basisCents:5000}:e),offers:page==='rewards'?[{id:'illustrative-offer',title:'School-day essentials',product:'example',rateBps:300,budgetCents:5000,reservedCents:150,endsAt:Date.parse('2026-10-19T12:00:00Z'),terms:'Illustrative purchase offer. Requires funded terms and provider activation.',treasury:wallet,createdAt:0}]:[],claims:page==='rewards'?[{id:'example',offerId:'illustrative-offer',orderId:'EXAMPLE-1842',owner:wallet,cents:150,status:t>3?'confirmed':'pending',createdAt:0}]:[],plan:page==='investing'?{goal:'A first apartment',targetCents:2500000,horizon:18,account:'parent',state:'NY',adult:true,savedAt:t>3?1:undefined}:null,premium:true,rewardReady:page==='rewards'},passports,provider:null,selectedAsset:'AAPL',search:'',year:'all',ledgerFilter:'all',onConnect:noop,onLock:noop,onRefresh:noop,onSearch:noop,onAsset:noop,onYear:noop,onFilter:noop,onAdd:noop,onImport:noop,onTemplate:noop,onExport:noop,onEdit:noop,onDelete:noop,onSync:noop,onConfirm:noop,onPlan:noop,onDeletePlan:noop,onDownloadPlan:noop,onProvider:noop,assetUrl:p=>staticFile(p.slice(1))};}
function Mark(){return <div className="fm-mark"><Img src={staticFile('brand/sprout-logo.png')}/>SPROUT</div>}
function Rise({children,t}:{children:React.ReactNode;t:number}){return <div style={{overflow:'hidden',paddingBottom:12,marginBottom:-12}}><div style={{transform:`translateY(${(1-at(t))*115}%)`}}>{children}</div></div>}
function Cursor({x,y,click=false}:{x:number;y:number;click?:boolean}){return <div style={{position:'absolute',left:x,top:y,zIndex:20,transform:`scale(${click?.88:1})`}}>{click&&<div style={{position:'absolute',left:-15,top:-15,width:50,height:50,borderRadius:'50%',border:'2px solid #ec793c',background:'#ec793c20'}}/>}<svg width="28" height="35" viewBox="0 0 28 35"><path d="M2 2L25 22L15 23L10 33L2 2Z" fill={C.ink} stroke="white" strokeWidth="2"/></svg></div>}
function Flower({t,x,y,size=520,angle=0}:{t:number;x:number;y:number;size?:number;angle?:number}){const a=at(t,0,1.2);return <Img src={staticFile('art/harvest-bouquet.png')} style={{position:'absolute',left:x,top:y,width:size,height:size,objectFit:'contain',transformOrigin:'50% 90%',transform:`translateY(${(1-a)*180}px) rotate(${angle+(1-a)*-15+Math.sin(t*1.2)*1.4}deg) scale(${.55+.45*a})`,opacity:at(t,0,.25)}}/>}
function Label({number,title,sub,t}:{number:string;title:string;sub:string;t:number}){return <div className="fm-label"><div className="fm-kicker" style={{opacity:at(t)}}>{number} / THE SPROUT TOOLKIT</div><h1><Rise t={t-.05}>{title}</Rise></h1><p style={{opacity:at(t,.2)}}>{sub}</p></div>}
function Product({page,t,x=120,y=285,scale=1.17,scroll=0}:{page:ToolPage;t:number;x?:number;y?:number;scale?:number;scroll?:number}){return <div className="fm-window" style={{left:x,top:y,width:1440*scale,height:700,transform:`translateY(${(1-at(t))*65}px)`,opacity:at(t)}}><div className="fm-browser"><i/><i/><i/><span>SPROUT / {page==='tax'?'tax-garden':page==='passports'?'asset-passports':page==='investing'?'family-investing':page}</span><small>PRODUCT WALKTHROUGH</small></div><div style={{width:1440,transformOrigin:'0 0',transform:`scale(${scale}) translateY(${-scroll}px)`}} className={`fm-ui fm-${page}`}><ToolsView {...props(page,t)}/></div></div>}
function Footnote({text}:{text:string}){return <div className="fm-note">{text}</div>}
export function FamilyFilm(){const t=useCurrentFrame()/30;const [ready]=useState(()=>delayRender('SPROUT font'));useEffect(()=>{document.fonts.load('500 24px Satoshi').then(()=>continueRender(ready));},[ready]);let shot:React.ReactNode;
 if(t<4){shot=<AbsoluteFill style={{background:C.paper}}><div style={{position:'absolute',left:125,top:85}}><Mark/></div><div className="fm-opening"><div className="fm-kicker" style={{opacity:at(t,.1)}}>THE FAMILY TOOLKIT</div><h1><Rise t={t-.1}>More for your</Rise><Rise t={t-.3}><em>everyday.</em></Rise></h1><p style={{opacity:at(t,.7)}}>Little things. Thoughtfully connected.</p></div><Flower t={t-.15} x={1070} y={210} size={750} angle={-4}/><div className="fm-paper-tag" style={{transform:`translateY(${(1-at(t,.5))*200}px) rotate(-6deg)`,opacity:at(t,.5)}}>Built around<br/><em>your family.</em></div><Footnote text="A staged walkthrough of the new SPROUT toolkit."/></AbsoluteFill>}
 else if(t<10){const s=t-4;shot=<AbsoluteFill style={{background:C.sage}}><Label number="01" title="Know what you own." sub="Issuer. Rights. Availability. All in one place." t={s}/><Product page="passports" t={s} scale={1.15} scroll={30+155*at(s,2.1,1.1)}/><Cursor x={1395-440*at(s,1.6,1)} y={740-70*at(s,1.6,1)} click={s>3.1&&s<3.45}/><Footnote text="Robinhood Stock Tokens are unavailable to US persons. Asset Passports are educational."/></AbsoluteFill>}
 else if(t<17){const s=t-10;shot=<AbsoluteFill style={{background:C.paper}}><Label number="02" title="A little more back." sub="Review an offer. Follow the reward." t={s}/><Product page="rewards" t={s} scroll={60+390*at(s,2.1,1.4)}/><div className="fm-reward-seal" style={{opacity:at(s,3.15),transform:`translateY(${(1-at(s,3.15))*70}px) rotate(-5deg)`}}><span>EXAMPLE PURCHASE REWARD</span><strong>$1.50</strong><small>Confirmed · awaiting manual payout</small></div><Footnote text="Illustrative offer and reward. Requires funded terms, eligible purchase and provider activation."/></AbsoluteFill>}
 else if(t<24){const s=t-17;shot=<AbsoluteFill style={{background:C.sage}}><Label number="03" title="Every detail, together." sub="Fill the gaps. Keep the record. Export when ready." t={s}/><Product page="tax" t={s} scroll={20+65*at(s,1.7,1)}/><Cursor x={1440-140*at(s,2,.5)} y={680+170*at(s,4.7,.6)} click={(s>2.8&&s<3.15)||(s>5.5&&s<5.85)}/><div className="fm-small-note" style={{opacity:at(s,3.1)}}><span>✓</span> Missing basis, reviewed.</div><Footnote text="Example records. Estimates use entered values; no automatic tax-lot matching or tax filing."/></AbsoluteFill>}
 else if(t<30){const s=t-24;shot=<AbsoluteFill style={{background:C.paper}}><Label number="04" title="Make room for tomorrow." sub="A family goal. A clear ownership plan." t={s}/><Product page="investing" t={s} scroll={95+245*at(s,2,1)}/><Cursor x={520} y={820} click={s>3&&s<3.35}/><Footnote text="Planning is available. US brokerage account connection and investment execution are not enabled."/></AbsoluteFill>}
 else if(t<36){const s=t-30;shot=<AbsoluteFill style={{background:C.sage}}><Label number="05" title="Understand the why." sub="Ask Intelligence about the record in front of you." t={s}/><div className="fm-intelligence" style={{opacity:at(s),transform:`translateY(${(1-at(s))*65}px)`}}><div className="fm-intel-side"><Mark/><span>Intelligence</span><div>↗ Asset Passports</div><div>↗ Family records</div><div>↗ Purchase rewards</div><small>Selected context only.<br/>Shared when you send.</small></div><div className="fm-intel-main"><div className="fm-kicker">LIVE AI ANSWER / EXAMPLE RECORD</div><div className="fm-question">Why was the cost basis marked unknown?</div><div className="fm-answer" style={{opacity:at(s,.9),transform:`translateY(${(1-at(s,.9))*25}px)`}}><span className="fm-answer-mark">✳</span><h2>A blank field isn’t a zero.</h2><p>The cost basis is unknown here because the purchase record was entered manually without specifying the original amount paid.</p><div className="fm-source">↗ IRS digital asset reporting <span>Reviewed Sep 19, 2026</span></div><small>For education and information only. Not financial advice.</small></div></div></div><Footnote text="Actual AI response to an illustrative record. Live access requires verified token holdings."/></AbsoluteFill>}
 else{const s=t-36;shot=<AbsoluteFill style={{background:C.paper}}><div style={{position:'absolute',left:125,top:85}}><Mark/></div><div className="fm-ending"><h1><Rise t={s}>Good things,</Rise><Rise t={s-.12}><em>growing together.</em></Rise></h1><div className="fm-end-tools" style={{opacity:at(s,.3)}}>Passports · Rewards · Tax Garden<br/>Family Investing · Intelligence</div><p style={{opacity:at(s,.6)}}>Explore the SPROUT family toolkit.</p></div><Flower t={s} x={1130} y={220} size={680}/><div className="fm-ending-url" style={{opacity:at(s,.6)}}>SPROUT <span>Little by little. Together.</span></div><Footnote text="Product preview. Funded rewards and investment-provider availability depend on activation."/></AbsoluteFill>}
 const cuts=[4,10,17,24,30,36];const cut=cuts.find(c=>Math.abs(t-c)<.23);let wipe=null;if(cut!==undefined){const progress=clamp((t-cut+.23)/.46);wipe=<div style={{position:'absolute',inset:0,zIndex:50,background:cuts.indexOf(cut)%2?C.sage:C.paper,clipPath:`inset(0 ${Math.max(0,100-progress*220)}% 0 ${Math.max(0,(progress-.45)*190)}%)`}}/>;}
 return <AbsoluteFill style={{color:C.ink,fontFamily:'Satoshi'}}><Audio src={staticFile('audio/score.wav')} volume={.85}/>{shot}{wipe}</AbsoluteFill>;
}
